export enum ContactActionTypes {
    CONTACT_SUCCESS = 'CONTACT_SUCCESS',
    CONTACT_FAIL = 'CONTACT_FAIL',
    GET_CONTACT_SUCCESS = 'GET_CONTACT_SUCCESS',
    GET_CONTACT_FAIL = 'GET_CONTACT_FAIL',
}
