export enum HomeTypes {
    GET_CATEGORIES_SUCCESS = "GET-CATEGORIES-SUCCESS",
    GET_ORGANISATIONS_SUCCESS = "GET_ORGANISATIONS_SUCCESS",
    GET_DROPDOWN_SUCCESS = "GET_DROPDOWN_SUCCESS",
}



export enum FaqTypes {
    GET_FAQ_SUCCESS = "GET_FAQ_SUCCESS",
    GET_FAQ_ERROR = "GET_FAQ_ERROR"
}

